### ISSUE TITLE
Feature Request: FAQ/Documentation for self-hosting

### ISSUE THREAD

**Issue by ipkpjersi** [hummingbird-me/kitsu-server#1425]
Hi,

I have some questions (perhaps an FAQ might be a good idea) about self-hosting. I may be interested in self-hosting my own instance of Kitsu - in theory, this should be possible, right? Is there any documentation for how one would go about doing this? I see there's documentation for contributing to this project, but I don't see any wiki or anything for self-hosting.

For example, I couldn't help but notice it looks like there isn't any DB seeder for like a complete list of anime, so how would that work? How would you populate the database with a full list of anime?

Also, for self-hosting something like this, would you just run the API (kitsu-server), then download the front-end (kitsu-web) and just point the front-end to your own API?

Cheers.

**Comment by shomykohai** [comment]
> Hi,
> 
> I have some questions (perhaps an FAQ might be a good idea) about self-hosting. I may be interested in self-hosting my own instance of Kitsu - in theory, this should be possible, right? Is there any documentation for how one would go about doing this? I see there's documentation for contributing to this project, but I don't see any wiki or anything for self-hosting.
> 
> For example, I couldn't help but notice it looks like there isn't any DB seeder for like a complete list of anime, so how would that work? How would you populate the database with a full list of anime?
> 
> Also, for self-hosting something like this, would you just run the API (kitsu-server), then download the front-end (kitsu-web) and just point the front-end to your own API?
> 
> Cheers.

For building your local instance of Kitsu you should use the [kitsu-tools repo](https://github.com/hummingbird-me/kitsu-tools). 
[Here](https://github.com/hummingbird-me/kitsu-tools/wiki/Setting-up-a-development-environment#docker-recommended) you can find all the documentation needed!

**Comment by ipkpjersi** [comment]
Oh that's awesome, thanks!

I feel like what you typed would be great to add to the kitsu-server README.md, but I'm fine with closing this since you answered my question.
