### ISSUE TITLE
SSL Error with api

### ISSUE THREAD

**Issue by Polliog** [hummingbird-me/kitsu-server#1556]
Hi everytime i try to connect to the site or use the API in the last hours i receive only errors or blank pages. Is the domain still active?

**Comment by Ontonator** [comment]
kitsu.io now shows a domain expired message.

**Comment by Polliog** [comment]
they changed domain to https://kitsu.app/
for now the CDN is still offline

**Comment by Polliog** [comment]
UPDATE: The media links are now updated

**Comment by Polliog** [comment]
I will close the issue, all the status are being published on official twitter account (thx for the support):
https://x.com/HeyKitsu
